export { default as Arrow } from './ChevroIcon.vue';
export { default as Dashboard } from './DashboardIcon.vue';
export { default as Calendario } from './CalendarioIcon.vue';
export { default as Descanso } from './DescansoIcon.vue';
export { default as Projetos } from './ProjetosIcon.vue';
export { default as Times } from './TimesIcon.vue';
export { default as Integracoes } from './IntegracoesIcon.vue';
export { default as Beneficios } from './BeneficiosIcon.vue';
export { default as Documentos } from './DocumentoIcon.vue';
